services:
  # API server 
  web:
    restart: always
    build: .
    command: ["python3", "app/main.py"]
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    networks:
      - private
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      start_period: 15s
      interval: 10s
      timeout: 10s
      retries: 5

  # NGINX Proxy Server for HTTPS
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    depends_on:
      - web
    networks:
      - private
    healthcheck:
      test: ["CMD", "curl","-k", "-f", "https://localhost"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 5

  # Redis Cache
  cache:
    image: redis:7.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel debug --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./cache:/data
    networks:
      - private
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 5

  # MariaDB database for RMQ object definitions
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - private
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

# Network definition
networks:
  private:
    driver: bridge
