version: '3'

services:
  # API server 
  web:
    restart: always
    build: .
    command: ["python3", "app/main.py"]
    env_file:
          - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    networks:
      - private

  # NGINX Proxy Server for HTTPS
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    depends_on:
      - web
    networks:
      #- public
      - private

  # Redis Cache
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel debug --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ${PWD}/cache:/data
    networks:
      - private

  # MariaDB database for RMQ object definitions
  db:
    image: mariadb
    restart: always
    env_file:
          - .env
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
      # SQLModel has a limitation to define different size VARCHAR definitions. Due to that, create the table with anan initialization process
      - ${PWD}/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - private

# Network definition
networks:
  public:
    driver: bridge
  private:
    driver: bridge
    #internal: true
